apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-sigepa
  namespace: aplicaciones
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend-sigepa
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 33%
  template:
    metadata:
      labels:
        app: frontend-sigepa
    spec:
      containers:
        - name: frontend-sigepa
          image: <HARBOR_REGISTRY>/library/frontend-sigepa:<VERSION>
          ports:
            - containerPort: 3000
          imagePullPolicy: Always

---

apiVersion: v1
kind: Service
metadata:
  name: frontend-sigepa
  labels:
    app: frontend-sigepa
  namespace: aplicaciones
spec:
  ports:
    - name: http
      protocol: TCP
      port: 3000
      targetPort: 3000
  selector:
    app: frontend-sigepa

---


