export const GET_PERSONS = 'GET_PERSONS';
export const REGISTRAR_PERSONA = 'REGISTRAR_PERSONA';
export const ELIMINAR_PERSONA = 'ELIMINAR_PERSONA';
export const MODIFICAR_PERSONA = 'MODIFICAR_PERSONA';

export const GET_MODULOS = 'GET_MODULOS';
export const REGISTRAR_MODULO = 'REGISTRAR_MODULO';
export const ELIMINAR_MODULO = 'ELIMINAR_MODULO';
export const MODIFICAR_MODULO = 'MODIFICAR_MODULO';
export const AGREGAR_MODULO_ERROR = 'AGREGAR_MODULO_ERROR';



export const GET_SUBMODULOS = 'GET_SUBMODULOS';
export const REGISTRAR_SUBMODULO = 'REGISTRAR_SUBMODULO';
export const ELIMINAR_SUBMODULO = 'ELIMINAR_SUBMODULO';
export const MODIFICAR_SUBMODULO = 'MODIFICAR_SUBMODULO';
export const GET_MODULO_SUBMODULOS = 'GET_MODULO_SUBMODULOS';
export const AGREGAR_SUBMODULOS_ERROR = 'AGREGAR_SUBMODULOS_ERROR';

/**
 * Catalogos
 */
export const GET_TIPOS_APOYOS = 'GET_TIPOS_APOYOS';
export const REGISTRAR_TIPOS_APOYOS = 'REGISTRAR_TIPOS_APOYOS';
export const ELIMINAR_TIPOS_APOYOS = 'ELIMINAR_TIPOS_APOYOS';
export const MODIFICAR_TIPOS_APOYOS = 'MODIFICAR_TIPOS_APOYOS';

export const GET_TIPOS_BENEFICIARIOS = 'GET_TIPOS_BENEFICIARIOS';
export const REGISTRAR_TIPOS_BENEFICIARIOS = 'REGISTRAR_TIPOS_BENEFICIARIOS';
export const ELIMINAR_TIPOS_BENEFICIARIOS = 'ELIMINAR_TIPOS_BENEFICIARIOS';
export const MODIFICAR_TIPOS_BENEFICIARIOS = 'MODIFICAR_TIPOS_BENEFICIARIOS';
export const AGREGAR_TIPOS_BENEFICIARIOS_ERROR = 'AGREGAR_TIPOS_BENEFICIARIOS_ERROR';

export const GET_COMITE_SECRETARIAS = 'GET_COMITE_SECRETARIAS';
export const REGISTRAR_COMITE_SECRETARIAS = 'REGISTRAR_COMITE_SECRETARIAS';
export const ELIMINAR_COMITE_SECRETARIAS = 'ELIMINAR_COMITE_SECRETARIAS';
export const MODIFICAR_COMITE_SECRETARIAS = 'MODIFICAR_COMITE_SECRETARIAS';

export const GET_EDADES_BENEFICIARIOS = 'GET_EDADES_BENEFICIARIOS';
export const REGISTRAR_EDADES_BENEFICIARIOS = 'REGISTRAR_EDADES_BENEFICIARIOS';
export const ELIMINAR_EDADES_BENEFICIARIOS = 'ELIMINAR_EDADES_BENEFICIARIOS';
export const MODIFICAR_EDADES_BENEFICIARIOS = 'MODIFICAR_EDADES_BENEFICIARIOS';

export const GET_EDADES_BENEFICIARIOS_BY_ID = 'GET_EDADES_BENEFICIARIOS_BY_ID';

export const GET_MOTIVO_RECHAZOS = 'GET_MOTIVO_RECHAZOS';
export const REGISTRAR_MOTIVO_RECHAZOS = 'REGISTRAR_MOTIVO_RECHAZOS';
export const ELIMINAR_MOTIVO_RECHAZOS = 'ELIMINAR_MOTIVO_RECHAZOS';
export const MODIFICAR_MOTIVO_RECHAZOS = 'MODIFICAR_MOTIVO_RECHAZOS';
export const AGREGAR_MOTIVO_RECHAZOS_ERROR = 'AGREGAR_MOTIVO_RECHAZOS_ERROR';

export const GET_NUMERO_APOYOS = 'GET_NUMERO_APOYOS';
export const REGISTRAR_NUMERO_APOYOS = 'REGISTRAR_NUMERO_APOYOS';
export const ELIMINAR_NUMERO_APOYOS = 'ELIMINAR_NUMERO_APOYOS';
export const MODIFICAR_NUMERO_APOYOS = 'MODIFICAR_NUMERO_APOYOS';
export const AGREGAR_NUMERO_APOYOS_ERROR = 'AGREGAR_NUMERO_APOYOS_ERROR';

export const GET_PERIODICIDAD_APOYOS = 'GET_PERIODICIDAD_APOYOS';
export const REGISTRAR_PERIODICIDAD_APOYOS = 'REGISTRAR_PERIODICIDAD_APOYOS';
export const ELIMINAR_PERIODICIDAD_APOYOS = 'ELIMINAR_PERIODICIDAD_APOYOS';
export const MODIFICAR_PERIODICIDAD_APOYOS = 'MODIFICAR_PERIODICIDAD_APOYOS';
export const AGREGAR_PERIODICIDAD_APOYOS_ERROR = 'AGREGAR_PERIODICIDAD_APOYOS_ERROR';

export const GET_DOCUMENTOS_REQUISITOS = 'GET_DOCUMENTOS_REQUISITOS';
export const REGISTRAR_DOCUMENTOS_REQUISITOS = 'REGISTRAR_DOCUMENTOS_REQUISITOS';
export const ELIMINAR_DOCUMENTOS_REQUISITOS = 'ELIMINAR_DOCUMENTOS_REQUISITOS';
export const MODIFICAR_DOCUMENTOS_REQUISITOS = 'MODIFICAR_DOCUMENTOS_REQUISITOS';
export const VIGENCIA_DOCUMENTOS_REQUISITOS = 'VIGENCIA_DOCUMENTOS_REQUISITOS';
export const GET_PROGRAMAS_DOCUMENTO = 'GET_PROGRAMAS_DOCUMENTO';
export const AGREGAR_DOCUMENTOS_ERROR = 'AGREGAR_DOCUMENTOS_ERROR';
export const GET_DOCUMENTOS_COMPLEMENTARIOS = 'GET_DOCUMENTOS_COMPLEMENTARIOS';

export const GET_VIGENCIAS = 'GET_VIGENCIAS';

export const GET_FIRMAS = 'GET_FIRMAS';
export const REGISTRAR_FIRMAS = 'REGISTRAR_FIRMAS';
export const ELIMINAR_FIRMAS = 'ELIMINAR_FIRMAS';
export const MODIFICAR_FIRMAS = 'MODIFICAR_FIRMAS';
export const AGREGAR_FIRMAS_ERROR = 'AGREGAR_FIRMAS_ERROR';

export const GET_CLASIFICACION_SERVICIOS = 'GET_CLASIFICACION_SERVICIOS';
export const REGISTRAR_CLASIFICACION_SERVICIOS = 'REGISTRAR_CLASIFICACION_SERVICIOS';
export const ELIMINAR_CLASIFICACION_SERVICIOS = 'ELIMINAR_CLASIFICACION_SERVICIOS';
export const MODIFICAR_CLASIFICACION_SERVICIOS = 'MODIFICAR_CLASIFICACION_SERVICIOS';
export const AGREGAR_CLASIFICACION_SERVICIOS_ERROR = 'AGREGAR_CLASIFICACION_SERVICIOS_ERROR';

/**
 * 
 */

export const GET_GENEROS = 'GET_GENEROS';
export const GET_ESTADO_CIVIL = 'GET_ESTADO_CIVIL';
export const REGISTRAR_BENEFICIARIO = 'REGISTRAR_BENEFICIARIO';
export const REGISTRAR_DIRECCION_BENEFICIARIO = 'REGISTRAR_DIRECCION_BENEFICIARIO';
export const GET_BENEFICIARIO = 'GET_BENEFICIARIO';
export const ACTUALIZAR_BENEFICIARIO = 'ACTUALIZAR_BENEFICIARIO';
export const OBTENER_DIRECCION = 'OBTENER_DIRECCION';
export const MODIFICAR_DIRECCION_BENEFICIARIO = 'MODIFICAR_DIRECCION_BENEFICIARIO';
export const GUARDAR_SOLICITUD_FOLIO = 'GUARDAR_SOLICITUD_FOLIO';
export const AGREGAR_SOLICITUD_FOLIO_ERROR = 'AGREGAR_SOLICITUD_FOLIO_ERROR';
export const BUSCAR_SOLICITUD_POR_PARAMETROS = 'BUSCAR_SOLICITUD_POR_PARAMETROS';
export const GET_BENEFICIARIO_MONETARIO = 'GET_BENEFICIARIO_MONETARIO';
export const GET_BENEFICIARIO_CANCELADO = 'GET_BENEFICIARIO_CANCELADO';
export const GET_BENEFICIARIO_REGISTRADO_PROGRAMA = 'GET_BENEFICIARIO_REGISTRADO_PROGRAMA';
export const BUSCAR_SOLICITUD_POR_PARAMETROS_BANDEJA = 'BUSCAR_SOLICITUD_POR_PARAMETROS_BANDEJA';
export const BUSCAR_SOLICITUD_POR_PARAMETROS_BANDEJA_APROBAR = 'BUSCAR_SOLICITUD_POR_PARAMETROS_BANDEJA_APROBAR';
export const CAMBIAR_ESTATUS_SOLICITUD_BANDEJA_VALIDADA = 'CAMBIAR_ESTATUS_SOLICITUD_BANDEJA_VALIDADA';
export const CAMBIAR_ESTATUS_SOLICITUD_BANDEJA_PENDIENTE = 'CAMBIAR_ESTATUS_SOLICITUD_BANDEJA_PENDIENTE';
export const CAMBIAR_ESTATUS_SOLICITUD_BANDEJA_APROBAR = 'CAMBIAR_ESTATUS_SOLICITUD_BANDEJA_APROBAR';
export const PROGRAMA_VIGENTE = ' PROGRAMA_VIGENTE';
export const CAMBIAR_ESTATUS_SOLICITUD_BANDEJA_REASIGNADA = 'CAMBIAR_ESTATUS_SOLICITUD_BANDEJA_REASIGNADA';
export const GET_COBERTURA_POR_PROGRAMA = 'GET_COBERTURA_POR_PROGRAMA';

export const GET_DOCUMENTOS_APOYO = 'GET_DOCUMENTOS_APOYO';
export const GUARDAR_DATOS_BOVEDA = 'GET_GUARDAR_DATOS_BOVEDA';
export const GET_EXISTE_DOCUMENTO = 'GET_EXISTE_DOCUMENTO';
export const ERROR_DOCUMENTO_BOVEDA = 'ERROR_DOCUMENTO_BOVEDA';

export const GET_SUBMODULOSBYPERFIL = 'GET_SUBMODULOSBYPERFIL';
export const REGISTRAR_SUBMODULOSBYPERFIL = 'REGISTRAR_SUBMODULOSBYPERFIL';
export const ELIMINAR_SUBMODULOSBYPERFIL = 'ELIMINAR_SUBMODULOSBYPERFIL';
export const MODIFICAR_SUBMODULOSBYPERFIL = 'MODIFICAR_SUBMODULOSBYPERFIL';


export const GET_CURSOS_CAPACITACIONES = 'GET_CURSOS_CAPACITACIONES';
export const REGISTRAR_CURSOS_CAPACITACIONES = 'REGISTRAR_CURSOS_CAPACITACIONES';
export const ELIMINAR_CURSOS_CAPACITACIONES = 'ELIMINAR_CURSOS_CAPACITACIONES';
export const MODIFICAR_CURSOS_CAPACITACIONES = 'MODIFICAR_CURSOS_CAPACITACIONES';
export const AGREGAR_CURSOS_CAPACITACIONES_ERROR = 'AGREGAR_CURSOS_CAPACITACIONES_ERROR';

export const GET_ACTIVIDADESCONTINUAR = 'GET_ACTIVIDADESCONTINUAR';
export const REGISTRAR_ACTIVIDADESCONTINUAR = 'REGISTRAR_ACTIVIDADESCONTINUAR';
export const ELIMINAR_ACTIVIDADESCONTINUAR = 'ELIMINAR_ACTIVIDADESCONTINUAR';
export const MODIFICAR_ACTIVIDADESCONTINUAR = 'MODIFICAR_ACTIVIDADESCONTINUAR';
export const AGREGAR_ACTIVIDADESCONTINUAR_ERROR = 'AGREGAR_ACTIVIDADESCONTINUAR_ERROR';

export const GET_BTACTIVIDADES = 'GET_BTACTIVIDADES';
export const REGISTRAR_BTACTIVIDADES = 'REGISTRAR_BTACTIVIDADES';
export const ELIMINAR_BTACTIVIDADES = 'ELIMINAR_BTACTIVIDADES';
export const MODIFICAR_BTACTIVIDADES = 'MODIFICAR_BTACTIVIDADES';

export const GET_APOYOSERVICIO = 'GET_APOYOSERVICIO';
export const REGISTRAR_APOYOSERVICIO = 'REGISTRAR_APOYOSERVICIO';
export const ELIMINAR_APOYOSERVICIO = 'ELIMINAR_APOYOSERVICIO';
export const MODIFICAR_APOYOSERVICIO = 'MODIFICAR_APOYOSERVICIO';
export const AGREGAR_APOYOSERVICIO_ERROR = 'AGREGAR_APOYOSERVICIO_ERROR';


export const GET_ESTADOS = 'GET_ESTADOS';
export const GET_ESTADO = 'GET_ESTADO';
export const REGISTRAR_ESTADOS = 'REGISTRAR_ESTADOS';
export const ELIMINAR_ESTADOS = 'ELIMINAR_ESTADOS';
export const MODIFICAR_ESTADOS = 'MODIFICAR_ESTADOS';
export const AGREGAR_ESTADOS_ERROR = 'AGREGAR_ESTADOS_ERROR';

export const GET_MUNICIPIOS = 'GET_MUNICIPIOS';
export const GET_MUNICIPIO = 'GET_MUNICIPIO';
export const REGISTRAR_MUNICIPIOS = 'REGISTRAR_MUNICIPIOS';
export const ELIMINAR_MUNICIPIOS = 'ELIMINAR_MUNICIPIOS';
export const MODIFICAR_MUNICIPIOS = 'MODIFICAR_MUNICIPIOS';
export const GET_MUNICIPIOS_ID = 'GET_MUNICIPIOS_ID';
export const AGREGAR_MUNICIPIOS_ERROR = 'AGREGAR_MUNICIPIOS_ERROR';

export const GET_REGIONMUNICIPIOS = 'GET_REGIONMUNICIPIOS';
export const GET_REGIONMUNICIPIO = 'GET_REGIONMUNICIPIO';
export const REGISTRAR_REGIONMUNICIPIOS = 'REGISTRAR_REGIONMUNICIPIOS';
export const ELIMINAR_REGIONMUNICIPIOS = 'ELIMINAR_REGIONMUNICIPIOS';
export const MODIFICAR_REGIONMUNICIPIOS = 'MODIFICAR_REGIONMUNICIPIOS';


export const REGISTRAR_PROGRAMAS = 'REGISTRAR_PROGRAMAS';

export const AGREGAR_PROGRAMA_EXITO = 'AGREGAR_PROGRAMA_EXITO';
export const AGREGAR_PROGRAMA_ERROR = 'AGREGAR_PROGRAMA_ERROR';
export const GET_PROGRAMAS = 'GET_PROGRAMAS';
export const ELIMINAR_PROGRAMAS = 'ELIMINAR_PROGRAMAS';
export const GET_PROGRAMAS_BY_ID = 'GET_PROGRAMAS_BY_ID';
export const MODIFICAR_PROGRAMAS = 'MODIFICAR_PROGRAMAS';
export const GET_PROGRAMASACTIVOS = 'GET_PROGRAMASACTIVOS';
export const GET_MUNICIPIOS_PROGRAMAS = 'GET_MUNICIPIOS_PROGRAMAS';
export const GET_DOCUMENTOS_PROGRAMAS = 'GET_DOCUMENTOS_PROGRAMAS';
export const GET_IMAGEN_PROGRAMAS = 'GET_IMAGEN_PROGRAMAS';
export const GET_PROGRAMAS_BY_URL = 'GET_PROGRAMAS_BY_URL';

export const CAMBIAR_PAGINA_PROGRAMAS = 'CAMBIAR_PAGINA_PROGRAMAS';
export const CAMBIAR_TAMANIO_PAGINA_PROGRAMAS = 'CAMBIAR_TAMANIO_PAGINA_PROGRAMAS';

export const GET_APOYOS = 'GET_APOYOS';
export const REGISTRAR_APOYOS = 'REGISTRAR_APOYOS';
export const ELIMINAR_APOYOS = 'ELIMINAR_APOYOS';
export const MODIFICAR_APOYOS = 'MODIFICAR_APOYOS';
export const AGREGAR_APOYOS_ERROR = 'AGREGAR_APOYOS_ERROR';


export const GET_LOCALIDADES = 'GET_LOCALIDADES';
export const REGISTRAR_LOCALIDADES = 'REGISTRAR_LOCALIDADES';
export const ELIMINAR_LOCALIDADES = 'ELIMINAR_LOCALIDADES';
export const MODIFICAR_LOCALIDADES = 'MODIFICAR_LOCALIDADES';
export const AGREGAR_LOCALIDADES_ERROR = 'AGREGAR_LOCALIDADES_ERROR';
export const GET_LOCALIDADES_BY_ID = 'GET_LOCALIDADES_BY_ID';
export const GET_LOCALIDADES_MUNICIPIO = 'GET_LOCALIDADES_MUNICIPIO';

export const CAMBIAR_PAGINA = 'CAMBIA_PAGINA';
export const CAMBIAR_TAMANIO_PAGINA = 'CAMBIA_TAMANIO_PAGINA';

export const GET_COMPLEMENTO_FURS = 'GET_COMPLEMENTO_FURS';
export const REGISTRAR_COMPLEMENTO_FURS = 'REGISTRAR_COMPLEMENTO_FURS';
export const ACTUALIZAR_COMPLEMENTO_FURS = 'ACTUALIZAR_COMPLEMENTO_FURS';


export const GET_ESTATUS_REGISTRO = 'GET_ESTATUS_REGISTRO';
export const REGISTRAR_ESTATUS_REGISTRO = 'REGISTRAR_ESTATUS_REGISTRO';
export const ELIMINAR_ESTATUS_REGISTRO = 'ELIMINAR_ESTATUS_REGISTRO';
export const MODIFICAR_ESTATUS_REGISTRO = 'MODIFICAR_ESTATUS_REGISTRO';
export const ESTATUS_REGISTRO_ERROR = 'ESTATUS_REGISTRO_ERROR';

export const GET_ESTATUS_SOLICITUD = 'GET_ESTATUS_SOLICITUD';
export const REGISTRAR_ESTATUS_SOLICITUD = 'REGISTRAR_ESTATUS_SOLICITUD';
export const ELIMINAR_ESTATUS_SOLICITUD = 'ELIMINAR_ESTATUS_SOLICITUD';
export const MODIFICAR_ESTATUS_SOLICITUD = 'MODIFICAR_ESTATUS_SOLICITUD';
export const ESTATUS_SOLICITUD_ERROR = 'ESTATUS_SOLICITUD_ERROR';

export const GET_ESTADOS_CIVIL = 'GET_ESTADOS_CIVIL';
export const REGISTRAR_ESTADOS_CIVIL = 'REGISTRAR_ESTADOS_CIVIL';
export const ELIMINAR_ESTADOS_CIVIL = 'ELIMINAR_ESTATUS_REGISTRO';
export const MODIFICAR_ESTADOS_CIVIL = 'MODIFICAR_ESTADOS_CIVIL';
export const ESTADOS_CIVIL_ERROR = 'ESTADOS_CIVIL_ERROR';

export const GET_GENERO = 'GET_GENERO';
export const REGISTRAR_GENERO = 'REGISTRAR_GENERO';
export const ELIMINAR_GENERO = 'ELIMINAR_GENERO';
export const MODIFICAR_GENERO = 'MODIFICAR_GENERO';
export const GENERO_ERROR = 'GENERO_ERROR';

export const GET_GRADO_ESTUDIOS = 'GET_GRADO_ESTUDIOS';
export const REGISTRAR_GRADO_ESTUDIOS = 'REGISTRAR_GRADO_ESTUDIOS';
export const ELIMINAR_GRADO_ESTUDIOS = 'ELIMINAR_GRADO_ESTUDIOS';
export const MODIFICAR_GRADO_ESTUDIOS = 'MODIFICAR_GRADO_ESTUDIOS';
export const GRADO_ESTUDIOS_ERROR = 'GRADO_ESTUDIOS_ERROR';

export const GET_IDENTIFICACIONES_OFICIALES = 'GET_IDENTIFICACIONES_OFICIALES';
export const REGISTRAR_IDENTIFICACIONES_OFICIALES = 'REGISTRAR_IDENTIFICACIONES_OFICIALES';
export const ELIMINAR_IDENTIFICACIONES_OFICIALES = 'ELIMINAR_IDENTIFICACIONES_OFICIALES';
export const MODIFICAR_IDENTIFICACIONES_OFICIALES = 'MODIFICAR_IDENTIFICACIONES_OFICIALES';
export const IDENTIFICACIONES_OFICIALES_ERROR = 'IDENTIFICACIONES_OFICIALES_ERROR';


export const GET_ORIGENES_SOLICITUD = 'GET_ORIGENES_SOLICITUD';
export const REGISTRAR_ORIGENES_SOLICITUD = 'REGISTRAR_ORIGENES_SOLICITUD';
export const ELIMINAR_ORIGENES_SOLICITUD = 'ELIMINAR_ORIGENES_SOLICITUD';
export const MODIFICAR_ORIGENES_SOLICITUD = 'MODIFICAR_ORIGENES_SOLICITUD';
export const ORIGENES_SOLICITUD_ERROR = 'ORIGENES_SOLICITUD_ERROR';

export const GET_EXPEDIENTE_PARAMETROS = 'GET_EXPEDIENTE_PARAMETROS';
export const ACTUALIZAR_EXPEDIENTE = 'ACTUALIZAR_EXPEDIENTE';
export const GET_ULTIMO_PROGRAMA_BENEFICIARIO = 'GET_ULTIMO_PROGRAMA_BENEFICIARIO';
export const GET_SOLICITUDES_EXPEDIENTE_BENEFICIARIO = "GET_SOLICITUDES_EXPEDIENTE_BENEFICIARIO";
export const GET_SOLICITUD_BENEFICIARIO_PROGRAMA = "GET_SOLICITUD_BENEFICIARIO_PROGRAMA";
export const REGISTRAR_BANDEJA_MOTIVO_RECHAZO = "REGISTRAR_BANDEJA_MOTIVO_RECHAZO";

export const GET_PADRON_BENEFICIARIOS = 'GET_PADRON_BENEFICIARIOS';
export const GET_DETALLE_PADRON_BENEFICIARIOS = 'GET_DETALLE_PADRON_BENEFICIARIOS';


export const GET_BANDEJA_RECHAZOS = 'GET_BANDEJA_RECHAZOS';
export const REGISTRAR_BANDEJA_RECHAZOS = 'REGISTRAR_BANDEJA_RECHAZOS';
export const ELIMINAR_BANDEJA_RECHAZOS = 'ELIMINAR_BANDEJA_RECHAZOS';
export const MODIFICAR_BANDEJA_RECHAZOS = 'MODIFICAR_BANDEJA_RECHAZOS';
export const BANDEJA_RECHAZOS_ERROR = 'BANDEJA_RECHAZOS_ERROR';
export const ACTUALIZAR_BANDEJA_MOTIVO_RECHAZO = 'ACTUALIZAR_BANDEJA_MOTIVO_RECHAZO';

/* API EXPEDIENTE */
export const GET_ETAPAS_BY_PLANTILLA = 'GET_ETAPAS_BY_PLANTILLA';
export const GET_DOCUMENTOS_BY_ETAPA_EXPEDIENTE = 'GET_DOCUMENTOS_BY_ETAPA_EXPEDIENTE';
export const GET_CONTENIDO_DOCUMENTO = 'GET_CONTENIDO_DOCUMENTO';
export const AGREGAR_CONTENIDO_DOCUMENTO = 'AGREGAR_CONTENIDO_DOCUMENTO';
export const DESHABILITAR_DOCUMENTO_EXPEDIENTE = 'DESHABILITAR_DOCUMENTO_EXPEDIENTE';
export const GET_EXPEDIENTE_BOVEDA_BY_BENEFICIARIO = 'GET_EXPEDIENTE_BOVEDA_BY_BENEFICIARIO';
export const GENERAR_EXPEDIENTE_PDF = 'GENERAR_EXPEDIENTE_PDF';



export const GET_TIPO_REQUISITOS = 'GET_TIPO_REQUISITOS';
export const REGISTRARc_TIPO_REQUISITOS = 'REGISTRAR_TIPO_REQUISITOS';
export const ELIMINAR_TIPO_REQUISITOS = 'ELIMINAR_TIPO_REQUISITOS';
export const MODIFICAR_TIPO_REQUISITOS = 'MODIFICAR_TIPO_REQUISITOS';
export const TIPO_REQUISITOS_ERROR = 'TIPO_REQUISITOS_ERROR';

export const GET_EMBOZO_TARJETAS = 'GET_EMBOZO_TARJETAS';
export const GUARDAR_EMBOZO_TARJETAS = 'GUARDAR_EMBOZO_TARJETAS';


export const GET_TARJETAS_EMBOZADAS = 'GET_TARJETAS_EMBOZADAS';
export const REGISTRAR_TARJETAS_EMBOZADAS = 'REGISTRAR_TARJETAS_EMBOZADAS';
export const REGISTRAR_TARJETAS_EMBOZADAS_ERROR = 'REGISTRAR_TARJETAS_EMBOZADAS_ERROR';


export const GET_MOTIVO_SUSPENSION = 'GET_MOTIVO_SUSPENSION';
export const REGISTRAR_MOTIVO_SUSPENSION = 'REGISTRAR_MOTIVO_SUSPENSION';
export const ELIMINAR_MOTIVO_SUSPENSION = 'ELIMINAR_MOTIVO_SUSPENSION';
export const MODIFICAR_MOTIVO_SUSPENSION = 'MODIFICAR_MOTIVO_SUSPENSION';
export const AGREGAR_MOTIVO_SUSPENSION_ERROR = 'AGREGAR_MOTIVO_SUSPENSION_ERROR';
export const GET_BANDEJA_SUSPENSION = 'GET_BANDEJA_SUSPENSION';

export const REGISTRAR_BANDEJA_SUSPENSION = 'REGISTRAR_BANDEJA_SUSPENSION';
