export const GET_PERSONS = 'GET_PERSONS';
export const REGISTRAR_PERSONA = 'REGISTRAR_PERSONA';
export const ELIMINAR_PERSONA = 'ELIMINAR_PERSONA';
export const MODIFICAR_PERSONA = 'MODIFICAR_PERSONA';

export const GET_MODULOS = 'GET_MODULOS';
export const REGISTRAR_MODULO = 'REGISTRAR_MODULO';
export const ELIMINAR_MODULO = 'ELIMINAR_MODULO';
export const MODIFICAR_MODULO = 'MODIFICAR_MODULO';