export const GET_PERSONS = 'GET_PERSONS';
export const REGISTRAR_PERSONA = 'REGISTRAR_PERSONA';
export const ELIMINAR_PERSONA = 'ELIMINAR_PERSONA';
export const MODIFICAR_PERSONA = 'MODIFICAR_PERSONA';

export const GET_MODULOS = 'GET_MODULOS';
export const REGISTRAR_MODULO = 'REGISTRAR_MODULO';
export const ELIMINAR_MODULO = 'ELIMINAR_MODULO';
export const MODIFICAR_MODULO = 'MODIFICAR_MODULO';


export const GET_SUBMODULOS = 'GET_SUBMODULOS';
export const REGISTRAR_SUBMODULO = 'REGISTRAR_SUBMODULO';
export const ELIMINAR_SUBMODULO = 'ELIMINAR_SUBMODULO';
export const MODIFICAR_SUBMODULO = 'MODIFICAR_SUBMODULO';
export const GET_MODULO_SUBMODULOS = 'GET_MODULO_SUBMODULOS';

/**
 * Catalogos
 */
export const GET_TIPOS_APOYOS = 'GET_TIPOS_APOYOS';
export const REGISTRAR_TIPOS_APOYOS = 'REGISTRAR_TIPOS_APOYOS';
export const ELIMINAR_TIPOS_APOYOS = 'ELIMINAR_TIPOS_APOYOS';
export const MODIFICAR_TIPOS_APOYOS = 'MODIFICAR_TIPOS_APOYOS';

export const GET_TIPOS_BENEFICIARIOS = 'GET_TIPOS_BENEFICIARIOS';
export const REGISTRAR_TIPOS_BENEFICIARIOS = 'REGISTRAR_TIPOS_BENEFICIARIOS';
export const ELIMINAR_TIPOS_BENEFICIARIOS = 'ELIMINAR_TIPOS_BENEFICIARIOS';
export const MODIFICAR_TIPOS_BENEFICIARIOS = 'MODIFICAR_TIPOS_BENEFICIARIOS';

export const GET_COMITE_SECRETARIAS = 'GET_COMITE_SECRETARIAS';
export const REGISTRAR_COMITE_SECRETARIAS = 'REGISTRAR_COMITE_SECRETARIAS';
export const ELIMINAR_COMITE_SECRETARIAS = 'ELIMINAR_COMITE_SECRETARIAS';
export const MODIFICAR_COMITE_SECRETARIAS = 'MODIFICAR_COMITE_SECRETARIAS';

export const GET_EDADES_BENEFICIARIOS = 'GET_EDADES_BENEFICIARIOS';
export const REGISTRAR_EDADES_BENEFICIARIOS = 'REGISTRAR_EDADES_BENEFICIARIOS';
export const ELIMINAR_EDADES_BENEFICIARIOS = 'ELIMINAR_EDADES_BENEFICIARIOS';
export const MODIFICAR_EDADES_BENEFICIARIOS = 'MODIFICAR_EDADES_BENEFICIARIOS';

export const GET_MOTIVO_RECHAZOS = 'GET_MOTIVO_RECHAZOS';
export const REGISTRAR_MOTIVO_RECHAZOS = 'REGISTRAR_MOTIVO_RECHAZOS';
export const ELIMINAR_MOTIVO_RECHAZOS = 'ELIMINAR_MOTIVO_RECHAZOS';
export const MODIFICAR_MOTIVO_RECHAZOS = 'MODIFICAR_MOTIVO_RECHAZOS';

export const GET_NUMERO_APOYOS = 'GET_NUMERO_APOYOS';
export const REGISTRAR_NUMERO_APOYOS = 'REGISTRAR_NUMERO_APOYOS';
export const ELIMINAR_NUMERO_APOYOS = 'ELIMINAR_NUMERO_APOYOS';
export const MODIFICAR_NUMERO_APOYOS = 'MODIFICAR_NUMERO_APOYOS';

export const GET_PERIODICIDAD_APOYOS = 'GET_PERIODICIDAD_APOYOS';
export const REGISTRAR_PERIODICIDAD_APOYOS = 'REGISTRAR_PERIODICIDAD_APOYOS';
export const ELIMINAR_PERIODICIDAD_APOYOS = 'ELIMINAR_PERIODICIDAD_APOYOS';
export const MODIFICAR_PERIODICIDAD_APOYOS = 'MODIFICAR_PERIODICIDAD_APOYOS';
/**
 * 
 */

export const GET_SUBMODULOSBYPERFIL = 'GET_SUBMODULOSBYPERFIL';
export const REGISTRAR_SUBMODULOSBYPERFIL = 'REGISTRAR_SUBMODULOSBYPERFIL';
export const ELIMINAR_SUBMODULOSBYPERFIL = 'ELIMINAR_SUBMODULOSBYPERFIL';
export const MODIFICAR_SUBMODULOSBYPERFIL = 'MODIFICAR_SUBMODULOSBYPERFIL';


export const GET_CURSOS_CAPACITACIONES = 'GET_CURSOS_CAPACITACIONES';
export const REGISTRAR_CURSOS_CAPACITACIONES = 'REGISTRAR_CURSOS_CAPACITACIONES';
export const ELIMINAR_CURSOS_CAPACITACIONES = 'ELIMINAR_CURSOS_CAPACITACIONES';
export const MODIFICAR_CURSOS_CAPACITACIONES = 'MODIFICAR_CURSOS_CAPACITACIONES';

export const GET_ACTIVIDADESCONTINUAR = 'GET_ACTIVIDADESCONTINUAR';
export const REGISTRAR_ACTIVIDADESCONTINUAR = 'REGISTRAR_ACTIVIDADESCONTINUAR';
export const ELIMINAR_ACTIVIDADESCONTINUAR = 'ELIMINAR_ACTIVIDADESCONTINUAR';
export const MODIFICAR_ACTIVIDADESCONTINUAR = 'MODIFICAR_ACTIVIDADESCONTINUAR';

export const GET_BTACTIVIDADES = 'GET_BTACTIVIDADES';
export const REGISTRAR_BTACTIVIDADES = 'REGISTRAR_BTACTIVIDADES';
export const ELIMINAR_BTACTIVIDADES = 'ELIMINAR_BTACTIVIDADES';
export const MODIFICAR_BTACTIVIDADES = 'MODIFICAR_BTACTIVIDADES';
