
export const types = {

    tipoBandejaSetActive: '[tipo bandeja] Set Active',
    tipoBandejaAddNew: '[tipo bandeja] Add new',
    tipoBandejaUpdated: '[tipo bandeja] Updated ',
    tipoBandejaLoaded: '[tipo bandeja] Tipo Bandeja loaded',

    bandejaLoaded: '[bandeja] Bandeja loaded',


    etapaSetActive: '[etapa] Etapa Set Active',
    etapaAddNew: '[etapa] Etapa Add new',
    etapaUpdated: '[etapa] Etapa Updated ',
    etapaLoaded: '[etapa] Etapa loaded',
    etapaDeleted: '[etapa] Etapa delete',
    arbolLoaded: '[arbol] Arbol loaded',
    arbolClear: '[arbol] Clear arbol',

}


export const typesArchivo = {

    tipoArchivoSetActive: '[tipo archivo] Set Active',
    tipoArchivoAddNew: '[tipo archivo] Add new',
    tipoArchivoUpdated: '[tipo archivo] Updated ',
    tipoArchivoLoaded: '[tipo archivo] Tipo Archivo loaded'
}

export const typesClave = {

    claveDocumentoSetActive: '[clave documento] Set Active',
    claveDocumentoAddNew: '[clave documento] Add new',
    claveDocumentoUpdated: '[clave documento] Updated ',
    claveDocumentoLoaded: '[clave documento] Clave Documento loaded'
}

export const typesRolesExpDig = {

    rolExpDigSetActive: '[rol exp dig] Set Active',
    rolExpDigAddNew: '[rol exp dig] Add new',
    rolExpDigUpdated: '[rol exp dig] Updated ',
    rolExpDigLoaded: '[rol exp dig] Rol Exp Dig loaded'
}

export const typesSesion = {
    COMENZAR_CIERRE_SESION: 'COMENZAR_CIERRE_SESION',
    CIERRE_SESION_EXITOSO: 'CIERRE_SESION_EXITOSO',
    CIERRE_SESION_ERROR: 'CIERRE_SESION_ERROR'
}

export const typesKeycloak = {

    COMENZAR_DESCARGA_KEYCLOAK: 'COMENZAR_DESCARGA_KEYCLOAK',
    DESCARGA_KEYCLOAK_EXITO: 'DESCARGA_KEYCLOAK_EXITO',
    DESCARGA_KEYCLOAK_ERROR: 'DESCARGA_KEYCLOAK_ERROR'
}


export const typesPerfilSubmodulo = {

    COMENZAR_DESCARGA_PERFILSUBMODULO: 'COMENZAR_DESCARGA_PERFILSUBMODULO',
    DESCARGA_PERFILSUBMODULO_EXITO: 'DESCARGA_PERFILSUBMODULO_EXITO',
    DESCARGA_PERFILSUBMODULO_ERROR: 'DESCARGA_PERFILSUBMODULO_ERROR',

    AGREGAR_PERFILSUBMODULO: 'AGREGAR_PERFILSUBMODULO',
    AGREGAR_PERFILSUBMODULO_EXITO: 'AGREGAR_PERFILSUBMODULO_EXITO',
    AGREGAR_PERFILSUBMODULO_ERROR: 'AGREGAR_PERFILSUBMODULO_ERROR',

    OBTENER_PERFILSUBMODULO_ELIMINAR: 'OBTENER_PERFILSUBMODULO_ELIMINAR',
    PERFILSUBMODULO_ELIMINADO_EXITO: 'PERFILSUBMODULO_ELIMINADO_EXITO',
    PERFILSUBMODULO_ELIMINADO_ERROR: 'PERFILSUBMODULO_ELIMINADO_ERROR',

    OBTENER_PERFILSUBMODULO_EDITAR: 'OBTENER_PERFILSUBMODULO_EDITAR',
    COMENZAR_EDICION_PERFILSUBMODULO: 'COMENZAR_EDICION_PERFILSUBMODULO',
    PERFILSUBMODULO_EDITADO_EXITO: 'PERFILSUBMODULO_EDITADO_EXITO',
    PERFILSUBMODULO_EDITADO_ERROR: 'PERFILSUBMODULO_EDITADO_ERROR',

    OBTENER_PERFILSUBMODULO_DELETE: 'OBTENER_PERFILSUBMODULO_DELETE',
    COMENZAR_DELETE_PERFILSUBMODULO: 'COMENZAR_DELETE_PERFILSUBMODULO',
    PERFILSUBMODULO_DELETE_EXITO: 'PERFILSUBMODULO_DELETE_EXITO',
    PERFILSUBMODULO_DELETE_ERROR: 'PERFILSUBMODULO_DELETE_ERROR',

    MOSTRAR_ALERTA: 'MOSTRAR_ALERTA',
    OCULTAR_ALERTA: 'OCULTAR_ALERTA',

}

export const typesTipoApoyo = {
    COMENZAR_DESCARGA_TIPOAPOYO: 'COMENZAR_DESCARGA_TIPOAPOYO',
    DESCARGA_TIPOAPOYO_EXITO: 'DESCARGA_TIPOAPOYO_EXITO',
    DESCARGA_TIPOAPOYO_ERROR: 'DESCARGA_TIPOAPOYO_ERROR',

    AGREGAR_TIPOAPOYO: 'AGREGAR_TIPOAPOYO',
    AGREGAR_TIPOAPOYO_EXITO: 'AGREGAR_TIPOAPOYO_EXITO',
    AGREGAR_TIPOAPOYO_ERROR: 'AGREGAR_TIPOAPOYO_ERROR',

    OBTENER_TIPOAPOYO_ELIMINAR: 'OBTENER_TIPOAPOYO_ELIMINAR',
    TIPOAPOYO_ELIMINADO_EXITO: 'TIPOAPOYO_ELIMINADO_EXITO',
    TIPOAPOYO_ELIMINADO_ERROR: 'TIPOAPOYO_ELIMINADO_ERROR',

    OBTENER_TIPOAPOYO_EDITAR: 'OBTENER_TIPOAPOYO_EDITAR',
    COMENZAR_EDICION_TIPOAPOYO: 'COMENZAR_EDICION_TIPOAPOYO',
    TIPOAPOYO_EDITADO_EXITO: 'TIPOAPOYO_EDITADO_EXITO',
    TIPOAPOYO_EDITADO_ERROR: 'TIPOAPOYO_EDITADO_ERROR',

    MOSTRAR_ALERTA: 'MOSTRAR_ALERTA',
    OCULTAR_ALERTA: 'OCULTAR_ALERTA',


}



